services:
  php_cli:
    container_name: php_cli
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /usr/src
    volumes:
      - ./php.ini:/etc/php/8.1/cli/conf.d/php.ini
      - ./:/usr/src
